name: Linting Dockerfiles 🐳
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - ./builds/podman/Dockerfile
    - ./builds/actions-custom-runner/Dockerfile

 workflow_dispatch:

jobs:
    
  docker-lint:
    uses: ocpdude/reusable/.github/workflows/linter.yaml@main
    with:
      language: hadolint
